### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by thomashillyer** [McGillEUS/mcgilleus-2019#20]

**Comment by ATahma** [comment]
I tried using [Favicon.io](https://favicon.io/) to make the favicon, but I cannot see it on my browser (Firefox Desktop). 
However, it shows it on my mobile phone (Firefox for Android), so what is left from here on should be adding the 4 lines of code to every page (I don't know if there is any way around this), figuring out the lines of code required for different browsers and OS, and using proper images instead of autogenerated ones.
P.S. [this](https://realfavicongenerator.net/favicon_checker?protocol=http&site=mcgilleus.ca) might be helpful too

**Comment by thomashillyer** [comment]
You have to have separate favicon files for each browser, there are
websites that you can upload a single file and it will convert and give you
the code for maximum browser compatibility

**Comment by ATahma** [comment]
Okay so the issue was I had a typo in the directory name for the .ico images, it works on firefox desktop and phone. I'd like to get some feedback from somebody with an iphone/macbook/chrom browser to tell me if they can see the favicon

**Comment by ATahma** [comment]
Extended the transparent background to make it square. All pages have a favicon now.
Commit : b070136f1408e7c77cab252ecf2635011c02221f
