### ISSUE TITLE
Compress council photos

### ISSUE THREAD

**Issue by MaireadMaloney** [McGillEUS/mcgilleus-2019#23]

**Comment by ATahma** [comment]
So far, I did lossless compression using `jpegoptim` for individual photos and `optipng` for the frontpage council picture. 
The council picures' size was reduced 90%: 
`jpegoptim --size=90% *.jpg` in the img/vpPics directory.
For the front page photo, I used `optipng -o7 council1920.png` and this reduced the size by roughly 40%. However, since this is so far the only heavy picture in that page, I'll try it on to see how it goes until I add more photos.

**Comment by ATahma** [comment]
Well when I compare them to other websites images, we are still on the heavy side. I installed imgbot on this repo and am waiting for a pull request, otherwise I'll attempt to reduce the size more.

**Comment by ATahma** [comment]
The key to reducing their size was to literally resize them. I broguht down the size from 6000x4000 to 1200x800 using a short bash script executed in the vpPics directory:
```bash
for file in *.jpg; do convert $file -resize 1200x800 $file; done
```
This requires the package [imageMagick](https://wiki.archlinux.org/index.php/ImageMagick) which also does the compressing of the cover image:
```bash
convert council1920.jpg -compress JPEG council1920.jpg
```
So far, when I erase the cache and load the website, it loads pretty fast. There is a little more space for compression if it is required, but it might sacrifice image quality at this point.
